-- 00002_seed_exercises.sql
-- Seed the exercise library (240 exercises) from exercises.json
-- Idempotent: skips if exercises already exist.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM exercises LIMIT 1) THEN
    RAISE NOTICE 'Exercises already seeded, skipping.';
    RETURN;
  END IF;

  INSERT INTO exercises (name, aliases, muscle_group, secondary_muscles, equipment, movement_pattern, tracking_type, default_rep_tier, is_custom)
  VALUES
    ('Barbell bench press', ARRAY['Flat bench press', 'Bench press'], 'chest', ARRAY['triceps', 'front delts'], 'barbell', 'horizontal_press', 'weight_reps', 'heavy_compound', false),
    ('Incline barbell bench press', ARRAY['Incline bench press'], 'chest', ARRAY['triceps', 'front delts'], 'barbell', 'horizontal_press', 'weight_reps', 'heavy_compound', false),
    ('Decline barbell bench press', ARRAY['Decline bench press'], 'chest', ARRAY['triceps', 'front delts'], 'barbell', 'horizontal_press', 'weight_reps', 'heavy_compound', false),
    ('Close-grip bench press', ARRAY['CGBP'], 'triceps', ARRAY['chest', 'front delts'], 'barbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Dumbbell bench press', ARRAY['Flat dumbbell press', 'Dumbbell press'], 'chest', ARRAY['triceps', 'front delts'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Incline dumbbell press', ARRAY['Incline dumbbell bench press'], 'chest', ARRAY['triceps', 'front delts'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Decline dumbbell press', '{}', 'chest', ARRAY['triceps', 'front delts'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Smith machine bench press', ARRAY['Smith bench press'], 'chest', ARRAY['triceps', 'front delts'], 'smith_machine', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Smith machine incline press', ARRAY['Smith incline bench press'], 'chest', ARRAY['triceps', 'front delts'], 'smith_machine', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Machine chest press', ARRAY['Seated chest press', 'Chest press machine'], 'chest', ARRAY['triceps', 'front delts'], 'machine', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Machine incline chest press', ARRAY['Incline chest press machine'], 'chest', ARRAY['triceps', 'front delts'], 'machine', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Dumbbell fly', ARRAY['Flat dumbbell fly', 'DB fly'], 'chest', ARRAY['front delts'], 'dumbbell', 'fly', 'weight_reps', 'isolation', false),
    ('Incline dumbbell fly', ARRAY['Incline DB fly'], 'chest', ARRAY['front delts'], 'dumbbell', 'fly', 'weight_reps', 'isolation', false),
    ('Cable fly', ARRAY['Cable crossover', 'Standing cable fly'], 'chest', ARRAY['front delts'], 'cable', 'fly', 'weight_reps', 'isolation', false),
    ('Low cable fly', ARRAY['Low to high cable fly'], 'chest', ARRAY['front delts'], 'cable', 'fly', 'weight_reps', 'isolation', false),
    ('High cable fly', ARRAY['High to low cable fly'], 'chest', ARRAY['front delts'], 'cable', 'fly', 'weight_reps', 'isolation', false),
    ('Pec deck', ARRAY['Pec deck fly', 'Machine fly', 'Butterfly'], 'chest', ARRAY['front delts'], 'machine', 'fly', 'weight_reps', 'isolation', false),
    ('Torture fly', ARRAY['Machine chest fly'], 'chest', ARRAY['front delts'], 'machine', 'fly', 'weight_reps', 'isolation', false),
    ('Chest dip', ARRAY['Dip'], 'chest', ARRAY['triceps', 'front delts'], 'bodyweight', 'horizontal_press', 'bodyweight_reps', 'compound', false),
    ('Push-up', ARRAY['Press-up'], 'chest', ARRAY['triceps', 'front delts'], 'bodyweight', 'horizontal_press', 'reps_only', 'compound', false),
    ('Lat pulldown', ARRAY['Wide grip lat pulldown'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Close-grip lat pulldown', ARRAY['Narrow grip lat pulldown'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Reverse-grip lat pulldown', ARRAY['Underhand lat pulldown', 'Supinated lat pulldown'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Single-arm lat pulldown', ARRAY['One arm lat pulldown'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Machine lat pulldown', ARRAY['Plate loaded lat pulldown'], 'back', ARRAY['biceps', 'rear delts'], 'machine', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Pull-up', ARRAY['Chin-up overhand'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'bodyweight', 'vertical_pull', 'bodyweight_reps', 'compound', false),
    ('Chin-up', ARRAY['Underhand pull-up'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'bodyweight', 'vertical_pull', 'bodyweight_reps', 'compound', false),
    ('Neutral-grip pull-up', ARRAY['Hammer grip pull-up'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'bodyweight', 'vertical_pull', 'bodyweight_reps', 'compound', false),
    ('Assisted pull-up', ARRAY['Machine assisted pull-up'], 'back', ARRAY['biceps', 'rear delts'], 'machine', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Seated row', ARRAY['Seated cable row', 'Cable row'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Wide-grip seated row', ARRAY['Wide cable row'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Single-arm cable row', ARRAY['One arm cable row'], 'back', ARRAY['biceps', 'rear delts'], 'cable', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Machine seated row', ARRAY['Plate loaded row machine', 'Chest-supported row machine'], 'back', ARRAY['biceps', 'rear delts'], 'machine', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Barbell row', ARRAY['Bent-over barbell row', 'BB row'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Pendlay row', ARRAY['Dead-stop row'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Dumbbell row', ARRAY['Single-arm dumbbell row', 'One arm DB row'], 'back', ARRAY['biceps', 'rear delts'], 'dumbbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Chest-supported dumbbell row', ARRAY['Incline dumbbell row', 'Seal row dumbbell'], 'back', ARRAY['biceps', 'rear delts'], 'dumbbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('T-bar row', ARRAY['Landmine row'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Chest-supported T-bar row', ARRAY['Machine T-bar row'], 'back', ARRAY['biceps', 'rear delts'], 'machine', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Smith machine row', ARRAY['Smith bent-over row'], 'back', ARRAY['biceps', 'rear delts'], 'smith_machine', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Straight-arm pulldown', ARRAY['Lat prayer', 'Straight-arm pushdown'], 'back', ARRAY['core'], 'cable', 'vertical_pull', 'weight_reps', 'isolation', false),
    ('Cable pullover', ARRAY['Standing cable pullover'], 'back', ARRAY['chest', 'core'], 'cable', 'vertical_pull', 'weight_reps', 'isolation', false),
    ('Dumbbell pullover', ARRAY['DB pullover'], 'back', ARRAY['chest', 'core'], 'dumbbell', 'vertical_pull', 'weight_reps', 'isolation', false),
    ('Deadlift', ARRAY['Conventional deadlift', 'Barbell deadlift'], 'back', ARRAY['hamstrings', 'glutes', 'core', 'forearms'], 'barbell', 'hip_hinge', 'weight_reps', 'heavy_compound', false),
    ('Sumo deadlift', ARRAY['Wide stance deadlift'], 'back', ARRAY['hamstrings', 'glutes', 'quads', 'core'], 'barbell', 'hip_hinge', 'weight_reps', 'heavy_compound', false),
    ('Rack pull', ARRAY['Block pull'], 'back', ARRAY['hamstrings', 'glutes', 'forearms'], 'barbell', 'hip_hinge', 'weight_reps', 'heavy_compound', false),
    ('Hyperextension', ARRAY['Back extension', '45-degree back extension'], 'back', ARRAY['hamstrings', 'glutes'], 'bodyweight', 'hip_hinge', 'bodyweight_reps', 'isolation', false),
    ('Inverted row', ARRAY['Body row', 'Australian pull-up'], 'back', ARRAY['biceps', 'rear delts'], 'bodyweight', 'horizontal_pull', 'bodyweight_reps', 'compound', false),
    ('Overhead press', ARRAY['Military press', 'Barbell overhead press', 'OHP'], 'shoulders', ARRAY['triceps', 'core'], 'barbell', 'vertical_press', 'weight_reps', 'heavy_compound', false),
    ('Seated dumbbell overhead press', ARRAY['Seated dumbbell shoulder press', 'Seated DB press'], 'shoulders', ARRAY['triceps'], 'dumbbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Standing dumbbell overhead press', ARRAY['Standing DB shoulder press'], 'shoulders', ARRAY['triceps', 'core'], 'dumbbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Arnold press', ARRAY['Arnold dumbbell press'], 'shoulders', ARRAY['triceps'], 'dumbbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Smith machine overhead press', ARRAY['Smith machine shoulder press'], 'shoulders', ARRAY['triceps'], 'smith_machine', 'vertical_press', 'weight_reps', 'compound', false),
    ('Machine shoulder press', ARRAY['Shoulder press machine'], 'shoulders', ARRAY['triceps'], 'machine', 'vertical_press', 'weight_reps', 'compound', false),
    ('Dumbbell lateral raise', ARRAY['Lateral raise', 'Side raise', 'Side lateral raise'], 'shoulders', '{}', 'dumbbell', 'lateral_raise', 'weight_reps', 'small_isolation', false),
    ('Cable lateral raise', ARRAY['Cable side raise'], 'shoulders', '{}', 'cable', 'lateral_raise', 'weight_reps', 'small_isolation', false),
    ('Machine lateral raise', ARRAY['Lateral raise machine'], 'shoulders', '{}', 'machine', 'lateral_raise', 'weight_reps', 'small_isolation', false),
    ('Leaning cable lateral raise', ARRAY['Cross body cable lateral raise'], 'shoulders', '{}', 'cable', 'lateral_raise', 'weight_reps', 'small_isolation', false),
    ('Dumbbell front raise', ARRAY['Front raise'], 'shoulders', ARRAY['chest'], 'dumbbell', 'front_raise', 'weight_reps', 'small_isolation', false),
    ('Cable front raise', '{}', 'shoulders', ARRAY['chest'], 'cable', 'front_raise', 'weight_reps', 'small_isolation', false),
    ('Plate front raise', '{}', 'shoulders', ARRAY['chest'], 'barbell', 'front_raise', 'weight_reps', 'small_isolation', false),
    ('Rear delt cable pull', ARRAY['Cable face pull', 'Face pull', 'Rear delt pull'], 'shoulders', ARRAY['rear delts', 'traps'], 'cable', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Reverse pec deck', ARRAY['Reverse fly machine', 'Rear delt fly machine'], 'shoulders', ARRAY['rear delts', 'traps'], 'machine', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Dumbbell rear delt fly', ARRAY['Bent-over reverse fly', 'Rear delt raise'], 'shoulders', ARRAY['rear delts', 'traps'], 'dumbbell', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Cable rear delt fly', ARRAY['Reverse cable fly'], 'shoulders', ARRAY['rear delts', 'traps'], 'cable', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Barbell upright row', ARRAY['Upright row'], 'shoulders', ARRAY['traps', 'biceps'], 'barbell', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Dumbbell upright row', '{}', 'shoulders', ARRAY['traps', 'biceps'], 'dumbbell', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Cable upright row', '{}', 'shoulders', ARRAY['traps', 'biceps'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Barbell shrug', ARRAY['Shrug'], 'shoulders', ARRAY['traps'], 'barbell', 'shrug', 'weight_reps', 'isolation', false),
    ('Dumbbell shrug', ARRAY['DB shrug'], 'shoulders', ARRAY['traps'], 'dumbbell', 'shrug', 'weight_reps', 'isolation', false),
    ('Smith machine shrug', '{}', 'shoulders', ARRAY['traps'], 'smith_machine', 'shrug', 'weight_reps', 'isolation', false),
    ('Trap bar shrug', ARRAY['Hex bar shrug'], 'shoulders', ARRAY['traps'], 'barbell', 'shrug', 'weight_reps', 'isolation', false),
    ('Barbell curl', ARRAY['Standing barbell curl', 'BB curl'], 'biceps', ARRAY['forearms'], 'barbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('EZ bar curl', ARRAY['EZ curl', 'Easy bar curl'], 'biceps', ARRAY['forearms'], 'ez_bar', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Dumbbell curl', ARRAY['Standing dumbbell curl', 'DB curl', 'Dumbbell bicep curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Seated bicep curl', ARRAY['Seated dumbbell curl', 'Seated incline curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Incline dumbbell curl', ARRAY['Incline curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Hammer curl', ARRAY['Neutral grip curl'], 'biceps', ARRAY['forearms', 'brachialis'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Cable curl', ARRAY['Standing cable curl', 'Cable bicep curl'], 'biceps', ARRAY['forearms'], 'cable', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Cable hammer curl', ARRAY['Rope hammer curl', 'Cable rope curl'], 'biceps', ARRAY['forearms', 'brachialis'], 'cable', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Preacher curl', ARRAY['EZ bar preacher curl', 'Scott curl'], 'biceps', ARRAY['forearms'], 'ez_bar', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Dumbbell preacher curl', ARRAY['Single arm preacher curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Machine preacher curl', ARRAY['Preacher curl machine'], 'biceps', ARRAY['forearms'], 'machine', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Concentration curl', ARRAY['Seated concentration curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Spider curl', ARRAY['Prone incline curl'], 'biceps', ARRAY['forearms'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Machine bicep curl', ARRAY['Bicep curl machine'], 'biceps', ARRAY['forearms'], 'machine', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Reverse curl', ARRAY['EZ bar reverse curl'], 'biceps', ARRAY['forearms', 'brachialis'], 'ez_bar', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Cable bayesian curl', ARRAY['Bayesian curl'], 'biceps', ARRAY['forearms'], 'cable', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Tricep dip', ARRAY['Weighted dip', 'Parallel bar dip'], 'triceps', ARRAY['chest', 'front delts'], 'bodyweight', 'elbow_extension', 'bodyweight_reps', 'compound', false),
    ('Machine dip', ARRAY['Assisted dip machine', 'Dip machine'], 'triceps', ARRAY['chest', 'front delts'], 'machine', 'elbow_extension', 'weight_reps', 'compound', false),
    ('Rope pushdown', ARRAY['Tricep rope pushdown', 'Cable rope pushdown'], 'triceps', '{}', 'cable', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Cable pushdown', ARRAY['Tricep pushdown', 'Straight bar pushdown', 'V-bar pushdown'], 'triceps', '{}', 'cable', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Single-arm cable pushdown', ARRAY['One arm tricep pushdown'], 'triceps', '{}', 'cable', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Skullcrusher', ARRAY['Lying tricep extension', 'EZ bar skullcrusher', 'Nosebreaker'], 'triceps', '{}', 'ez_bar', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Dumbbell skullcrusher', ARRAY['Dumbbell lying tricep extension'], 'triceps', '{}', 'dumbbell', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Overhead tricep extension (cable)', ARRAY['Cable overhead extension', 'Rope overhead extension'], 'triceps', '{}', 'cable', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Overhead tricep extension (dumbbell)', ARRAY['Dumbbell overhead extension', 'French press dumbbell'], 'triceps', '{}', 'dumbbell', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Overhead tricep extension (EZ bar)', ARRAY['French press', 'EZ bar overhead extension'], 'triceps', '{}', 'ez_bar', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Tricep kickback', ARRAY['Dumbbell kickback'], 'triceps', '{}', 'dumbbell', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Cable kickback', ARRAY['Cable tricep kickback'], 'triceps', '{}', 'cable', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Machine tricep extension', ARRAY['Tricep extension machine'], 'triceps', '{}', 'machine', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Diamond push-up', ARRAY['Close grip push-up', 'Triangle push-up'], 'triceps', ARRAY['chest', 'front delts'], 'bodyweight', 'elbow_extension', 'reps_only', 'isolation', false),
    ('Barbell squat', ARRAY['Back squat', 'Squat'], 'quads', ARRAY['glutes', 'hamstrings', 'core'], 'barbell', 'squat', 'weight_reps', 'heavy_compound', false),
    ('Front squat', ARRAY['Barbell front squat'], 'quads', ARRAY['glutes', 'core'], 'barbell', 'squat', 'weight_reps', 'heavy_compound', false),
    ('Goblet squat', ARRAY['Dumbbell goblet squat'], 'quads', ARRAY['glutes', 'core'], 'dumbbell', 'squat', 'weight_reps', 'compound', false),
    ('Kettlebell squat', ARRAY['Kettlebell goblet squat', 'KB squat'], 'quads', ARRAY['glutes', 'core'], 'kettlebell', 'squat', 'weight_reps', 'compound', false),
    ('Smith machine squat', ARRAY['Smith squat'], 'quads', ARRAY['glutes', 'hamstrings'], 'smith_machine', 'squat', 'weight_reps', 'compound', false),
    ('Hack squat', ARRAY['Machine hack squat'], 'quads', ARRAY['glutes'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('Leg press', ARRAY['Machine leg press', '45 degree leg press'], 'quads', ARRAY['glutes', 'hamstrings'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('Horizontal leg press', ARRAY['Seated leg press'], 'quads', ARRAY['glutes', 'hamstrings'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('Pendulum squat', ARRAY['Pendulum squat machine'], 'quads', ARRAY['glutes'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('Belt squat', ARRAY['Belt squat machine'], 'quads', ARRAY['glutes'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('V-squat', ARRAY['V squat machine'], 'quads', ARRAY['glutes'], 'machine', 'squat', 'weight_reps', 'compound', false),
    ('Sissy squat', '{}', 'quads', '{}', 'bodyweight', 'squat', 'bodyweight_reps', 'isolation', false),
    ('Leg extension', ARRAY['Machine leg extension', 'Quad extension'], 'quads', '{}', 'machine', 'leg_extension', 'weight_reps', 'isolation', false),
    ('Single-leg extension', ARRAY['One leg extension'], 'quads', '{}', 'machine', 'leg_extension', 'weight_reps', 'isolation', false),
    ('Barbell lunge', ARRAY['Walking lunge barbell'], 'quads', ARRAY['glutes', 'hamstrings'], 'barbell', 'lunge', 'weight_reps', 'compound', false),
    ('Dumbbell lunge', ARRAY['Walking lunge', 'DB lunge'], 'quads', ARRAY['glutes', 'hamstrings'], 'dumbbell', 'lunge', 'weight_reps', 'compound', false),
    ('Reverse lunge', ARRAY['Dumbbell reverse lunge'], 'quads', ARRAY['glutes', 'hamstrings'], 'dumbbell', 'lunge', 'weight_reps', 'compound', false),
    ('Bulgarian split squat', ARRAY['Rear foot elevated split squat', 'RFESS'], 'quads', ARRAY['glutes', 'hamstrings'], 'dumbbell', 'lunge', 'weight_reps', 'compound', false),
    ('Smith machine lunge', ARRAY['Smith split squat'], 'quads', ARRAY['glutes', 'hamstrings'], 'smith_machine', 'lunge', 'weight_reps', 'compound', false),
    ('Step-up', ARRAY['Dumbbell step-up'], 'quads', ARRAY['glutes'], 'dumbbell', 'lunge', 'weight_reps', 'compound', false),
    ('Wall sit', ARRAY['Wall squat hold'], 'quads', '{}', 'bodyweight', 'squat', 'time', 'isolation', false),
    ('Romanian deadlift', ARRAY['RDL', 'Barbell RDL'], 'hamstrings', ARRAY['glutes', 'back'], 'barbell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Romanian deadlift (dumbbell)', ARRAY['Dumbbell RDL', 'DB Romanian deadlift'], 'hamstrings', ARRAY['glutes', 'back'], 'dumbbell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Single-leg Romanian deadlift', ARRAY['Single-leg RDL'], 'hamstrings', ARRAY['glutes', 'core'], 'dumbbell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Stiff-leg deadlift', ARRAY['Straight-leg deadlift', 'SLDL'], 'hamstrings', ARRAY['glutes', 'back'], 'barbell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Smith machine Romanian deadlift', ARRAY['Smith machine RDL'], 'hamstrings', ARRAY['glutes', 'back'], 'smith_machine', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Seated hamstring curl', ARRAY['Seated leg curl', 'Machine seated leg curl'], 'hamstrings', '{}', 'machine', 'leg_curl', 'weight_reps', 'isolation', false),
    ('Lying hamstring curl', ARRAY['Lying leg curl', 'Prone leg curl'], 'hamstrings', '{}', 'machine', 'leg_curl', 'weight_reps', 'isolation', false),
    ('Standing hamstring curl', ARRAY['Standing leg curl'], 'hamstrings', '{}', 'machine', 'leg_curl', 'weight_reps', 'isolation', false),
    ('Nordic hamstring curl', ARRAY['Nordic curl', 'Natural glute-ham raise'], 'hamstrings', ARRAY['glutes'], 'bodyweight', 'leg_curl', 'bodyweight_reps', 'compound', false),
    ('Glute-ham raise', ARRAY['GHR', 'GHD raise'], 'hamstrings', ARRAY['glutes', 'back'], 'bodyweight', 'leg_curl', 'bodyweight_reps', 'compound', false),
    ('Good morning', ARRAY['Barbell good morning'], 'hamstrings', ARRAY['glutes', 'back'], 'barbell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Barbell hip thrust', ARRAY['Hip thrust'], 'glutes', ARRAY['hamstrings'], 'barbell', 'hip_extension', 'weight_reps', 'compound', false),
    ('Smith machine hip thrust', '{}', 'glutes', ARRAY['hamstrings'], 'smith_machine', 'hip_extension', 'weight_reps', 'compound', false),
    ('Machine hip thrust', ARRAY['Hip thrust machine'], 'glutes', ARRAY['hamstrings'], 'machine', 'hip_extension', 'weight_reps', 'compound', false),
    ('Glute bridge', ARRAY['Bodyweight glute bridge'], 'glutes', ARRAY['hamstrings'], 'bodyweight', 'hip_extension', 'bodyweight_reps', 'isolation', false),
    ('Single-leg glute bridge', ARRAY['One leg glute bridge'], 'glutes', ARRAY['hamstrings'], 'bodyweight', 'hip_extension', 'bodyweight_reps', 'isolation', false),
    ('Cable pull-through', ARRAY['Pull-through'], 'glutes', ARRAY['hamstrings'], 'cable', 'hip_hinge', 'weight_reps', 'isolation', false),
    ('Cable kickback (glute)', ARRAY['Cable glute kickback'], 'glutes', '{}', 'cable', 'hip_extension', 'weight_reps', 'isolation', false),
    ('Machine glute kickback', ARRAY['Glute kickback machine'], 'glutes', '{}', 'machine', 'hip_extension', 'weight_reps', 'isolation', false),
    ('Hip abduction machine', ARRAY['Abductor machine', 'Seated hip abduction'], 'glutes', '{}', 'machine', 'hip_abduction', 'weight_reps', 'isolation', false),
    ('Hip adduction machine', ARRAY['Adductor machine', 'Seated hip adduction', 'Inner thigh machine'], 'quads', ARRAY['adductors'], 'machine', 'hip_adduction', 'weight_reps', 'isolation', false),
    ('Kettlebell swing', ARRAY['KB swing'], 'glutes', ARRAY['hamstrings', 'core', 'shoulders'], 'kettlebell', 'hip_hinge', 'weight_reps', 'compound', false),
    ('Standing calf raise', ARRAY['Machine calf raise'], 'calves', '{}', 'machine', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Seated calf raise', ARRAY['Machine seated calf raise'], 'calves', '{}', 'machine', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Smith machine calf raise', '{}', 'calves', '{}', 'smith_machine', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Leg press calf raise', ARRAY['Calf press'], 'calves', '{}', 'machine', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Dumbbell calf raise', ARRAY['Single leg calf raise'], 'calves', '{}', 'dumbbell', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Bodyweight calf raise', ARRAY['Standing calf raise bodyweight'], 'calves', '{}', 'bodyweight', 'calf_raise', 'reps_only', 'isolation', false),
    ('Crunch', ARRAY['Ab crunch'], 'abs', '{}', 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Machine crunch', ARRAY['Ab crunch machine', 'Seated crunch machine'], 'abs', '{}', 'machine', 'core_flexion', 'weight_reps', 'isolation', false),
    ('Cable crunch', ARRAY['Kneeling cable crunch'], 'abs', '{}', 'cable', 'core_flexion', 'weight_reps', 'isolation', false),
    ('Decline crunch', ARRAY['Decline sit-up'], 'abs', '{}', 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Hanging leg raise', ARRAY['Hanging knee raise'], 'abs', ARRAY['hip flexors'], 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Captain''s chair leg raise', ARRAY['Vertical knee raise'], 'abs', ARRAY['hip flexors'], 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Lying leg raise', ARRAY['Flat leg raise'], 'abs', ARRAY['hip flexors'], 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Ab wheel rollout', ARRAY['Ab roller'], 'abs', ARRAY['shoulders', 'back'], 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Russian twist', ARRAY['Seated twist'], 'abs', ARRAY['obliques'], 'bodyweight', 'core_rotation', 'reps_only', 'isolation', false),
    ('Cable woodchop', ARRAY['Wood chop', 'Cable rotation'], 'abs', ARRAY['obliques'], 'cable', 'core_rotation', 'weight_reps', 'isolation', false),
    ('Plank', ARRAY['Front plank', 'Forearm plank'], 'abs', ARRAY['core', 'shoulders'], 'bodyweight', 'core_stability', 'time', 'isolation', false),
    ('Side plank', '{}', 'abs', ARRAY['obliques'], 'bodyweight', 'core_stability', 'time', 'isolation', false),
    ('Dead bug', '{}', 'abs', ARRAY['core'], 'bodyweight', 'core_stability', 'reps_only', 'isolation', false),
    ('Pallof press', ARRAY['Cable Pallof press', 'Anti-rotation press'], 'abs', ARRAY['obliques', 'core'], 'cable', 'core_stability', 'weight_reps', 'isolation', false),
    ('Mountain climber', '{}', 'abs', ARRAY['hip flexors', 'shoulders'], 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Bicycle crunch', '{}', 'abs', ARRAY['obliques'], 'bodyweight', 'core_rotation', 'reps_only', 'isolation', false),
    ('Toe touch crunch', ARRAY['V-up'], 'abs', '{}', 'bodyweight', 'core_flexion', 'reps_only', 'isolation', false),
    ('Wrist curl', ARRAY['Barbell wrist curl', 'Forearm curl'], 'forearms', '{}', 'barbell', 'wrist_flexion', 'weight_reps', 'small_isolation', false),
    ('Reverse wrist curl', ARRAY['Wrist extension'], 'forearms', '{}', 'barbell', 'wrist_extension', 'weight_reps', 'small_isolation', false),
    ('Dumbbell wrist curl', ARRAY['DB wrist curl'], 'forearms', '{}', 'dumbbell', 'wrist_flexion', 'weight_reps', 'small_isolation', false),
    ('Farmer''s walk', ARRAY['Farmer''s carry'], 'forearms', ARRAY['traps', 'core'], 'dumbbell', 'carry', 'weight_reps', 'compound', false),
    ('Dead hang', ARRAY['Bar hang'], 'forearms', ARRAY['back', 'shoulders'], 'bodyweight', 'grip', 'time', 'isolation', false),
    ('Treadmill', ARRAY['Treadmill run', 'Treadmill walk'], 'quads', ARRAY['hamstrings', 'glutes', 'calves'], 'machine', 'cardio', 'distance_time', 'compound', false),
    ('Rowing machine', ARRAY['Erg', 'Concept 2', 'Indoor rower'], 'back', ARRAY['quads', 'hamstrings', 'biceps', 'core'], 'machine', 'cardio', 'distance_time', 'compound', false),
    ('Stationary bike', ARRAY['Exercise bike', 'Spin bike'], 'quads', ARRAY['hamstrings', 'glutes', 'calves'], 'machine', 'cardio', 'distance_time', 'compound', false),
    ('Elliptical', ARRAY['Cross trainer'], 'quads', ARRAY['hamstrings', 'glutes'], 'machine', 'cardio', 'distance_time', 'compound', false),
    ('Stair climber', ARRAY['StairMaster', 'Stair stepper'], 'quads', ARRAY['glutes', 'calves'], 'machine', 'cardio', 'distance_time', 'compound', false),
    ('Battle ropes', ARRAY['Heavy ropes'], 'shoulders', ARRAY['core', 'arms'], 'bodyweight', 'cardio', 'time', 'compound', false),
    ('Box jump', ARRAY['Plyometric box jump'], 'quads', ARRAY['glutes', 'calves'], 'bodyweight', 'plyometric', 'reps_only', 'compound', false),
    ('Burpee', '{}', 'quads', ARRAY['chest', 'shoulders', 'core'], 'bodyweight', 'full_body', 'reps_only', 'compound', false),
    ('Kettlebell clean and press', ARRAY['KB clean and press'], 'shoulders', ARRAY['core', 'glutes', 'back'], 'kettlebell', 'full_body', 'weight_reps', 'compound', false),
    ('Kettlebell snatch', ARRAY['KB snatch'], 'shoulders', ARRAY['core', 'glutes', 'back'], 'kettlebell', 'full_body', 'weight_reps', 'compound', false),
    ('Kettlebell Turkish get-up', ARRAY['Turkish get-up', 'TGU'], 'shoulders', ARRAY['core', 'glutes'], 'kettlebell', 'full_body', 'weight_reps', 'compound', false),
    ('Barbell clean', ARRAY['Power clean'], 'back', ARRAY['quads', 'glutes', 'shoulders', 'core'], 'barbell', 'full_body', 'weight_reps', 'heavy_compound', false),
    ('Barbell snatch', ARRAY['Power snatch'], 'back', ARRAY['shoulders', 'quads', 'glutes', 'core'], 'barbell', 'full_body', 'weight_reps', 'heavy_compound', false),
    ('Thruster', ARRAY['Barbell thruster'], 'quads', ARRAY['shoulders', 'glutes', 'core'], 'barbell', 'full_body', 'weight_reps', 'compound', false),
    ('Dumbbell thruster', ARRAY['DB thruster'], 'quads', ARRAY['shoulders', 'glutes', 'core'], 'dumbbell', 'full_body', 'weight_reps', 'compound', false),
    ('Landmine press', ARRAY['Single arm landmine press'], 'shoulders', ARRAY['chest', 'triceps', 'core'], 'barbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Landmine squat', '{}', 'quads', ARRAY['glutes', 'core'], 'barbell', 'squat', 'weight_reps', 'compound', false),
    ('Trap bar deadlift', ARRAY['Hex bar deadlift'], 'back', ARRAY['quads', 'hamstrings', 'glutes', 'core'], 'barbell', 'hip_hinge', 'weight_reps', 'heavy_compound', false),
    ('Deficit deadlift', '{}', 'back', ARRAY['hamstrings', 'glutes', 'core'], 'barbell', 'hip_hinge', 'weight_reps', 'heavy_compound', false),
    ('Pause squat', ARRAY['Paused barbell squat'], 'quads', ARRAY['glutes', 'hamstrings', 'core'], 'barbell', 'squat', 'weight_reps', 'heavy_compound', false),
    ('Zercher squat', '{}', 'quads', ARRAY['glutes', 'core', 'biceps'], 'barbell', 'squat', 'weight_reps', 'compound', false),
    ('Sumo squat', ARRAY['Wide stance squat', 'Plie squat'], 'quads', ARRAY['glutes', 'adductors'], 'dumbbell', 'squat', 'weight_reps', 'compound', false),
    ('Cossack squat', ARRAY['Lateral squat'], 'quads', ARRAY['glutes', 'adductors'], 'bodyweight', 'squat', 'bodyweight_reps', 'compound', false),
    ('Pistol squat', ARRAY['Single leg squat'], 'quads', ARRAY['glutes', 'core'], 'bodyweight', 'squat', 'bodyweight_reps', 'compound', false),
    ('Cable lateral lunge', '{}', 'quads', ARRAY['glutes', 'adductors'], 'cable', 'lunge', 'weight_reps', 'compound', false),
    ('Resistance band pull-apart', ARRAY['Band pull-apart'], 'shoulders', ARRAY['rear delts', 'traps'], 'resistance_band', 'rear_delt', 'reps_only', 'small_isolation', false),
    ('Resistance band face pull', ARRAY['Band face pull'], 'shoulders', ARRAY['rear delts', 'traps'], 'resistance_band', 'rear_delt', 'reps_only', 'small_isolation', false),
    ('Resistance band curl', ARRAY['Band bicep curl'], 'biceps', ARRAY['forearms'], 'resistance_band', 'elbow_flexion', 'reps_only', 'isolation', false),
    ('Resistance band row', ARRAY['Band row'], 'back', ARRAY['biceps', 'rear delts'], 'resistance_band', 'horizontal_pull', 'reps_only', 'compound', false),
    ('Resistance band squat', ARRAY['Band squat'], 'quads', ARRAY['glutes'], 'resistance_band', 'squat', 'reps_only', 'compound', false),
    ('Resistance band lateral walk', ARRAY['Band walk', 'Monster walk'], 'glutes', '{}', 'resistance_band', 'hip_abduction', 'reps_only', 'isolation', false),
    ('Bench press (dumbbell, neutral grip)', ARRAY['Neutral grip dumbbell press', 'Hammer grip press'], 'chest', ARRAY['triceps', 'front delts'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Floor press', ARRAY['Dumbbell floor press'], 'chest', ARRAY['triceps'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Barbell floor press', '{}', 'chest', ARRAY['triceps'], 'barbell', 'horizontal_press', 'weight_reps', 'heavy_compound', false),
    ('Meadows row', ARRAY['Landmine row single arm'], 'back', ARRAY['biceps', 'rear delts'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Seal row', ARRAY['Chest supported barbell row'], 'back', ARRAY['biceps', 'rear delts'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Lat pulldown (V-bar)', ARRAY['V-bar pulldown'], 'back', ARRAY['biceps'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Behind-the-neck lat pulldown', '{}', 'back', ARRAY['biceps', 'rear delts'], 'cable', 'vertical_pull', 'weight_reps', 'compound', false),
    ('Single-arm dumbbell overhead press', ARRAY['One arm DB press'], 'shoulders', ARRAY['triceps', 'core'], 'dumbbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Push press', ARRAY['Barbell push press'], 'shoulders', ARRAY['triceps', 'quads', 'core'], 'barbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Lu raise', ARRAY['Lu Xiaojun raise'], 'shoulders', '{}', 'dumbbell', 'lateral_raise', 'weight_reps', 'small_isolation', false),
    ('Prone Y raise', ARRAY['Y raise'], 'shoulders', ARRAY['traps'], 'dumbbell', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Zottman curl', '{}', 'biceps', ARRAY['forearms', 'brachialis'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Cross-body hammer curl', ARRAY['Pinwheel curl'], 'biceps', ARRAY['forearms', 'brachialis'], 'dumbbell', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('21s bicep curl', ARRAY['21s'], 'biceps', ARRAY['forearms'], 'ez_bar', 'elbow_flexion', 'weight_reps', 'isolation', false),
    ('Dumbbell bench press (single arm)', ARRAY['Single arm dumbbell press'], 'chest', ARRAY['triceps', 'core'], 'dumbbell', 'horizontal_press', 'weight_reps', 'compound', false),
    ('Cable chest press', ARRAY['Standing cable press'], 'chest', ARRAY['triceps', 'front delts'], 'cable', 'horizontal_press', 'weight_reps', 'isolation', false),
    ('Reverse grip barbell row', ARRAY['Underhand barbell row', 'Yates row'], 'back', ARRAY['biceps', 'rear delts'], 'barbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Kroc row', ARRAY['Heavy dumbbell row'], 'back', ARRAY['biceps', 'rear delts', 'forearms'], 'dumbbell', 'horizontal_pull', 'weight_reps', 'compound', false),
    ('Cable face pull (rope)', ARRAY['High cable face pull'], 'shoulders', ARRAY['rear delts', 'traps'], 'cable', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('Incline Y raise', ARRAY['Incline dumbbell Y raise'], 'shoulders', ARRAY['traps', 'rear delts'], 'dumbbell', 'rear_delt', 'weight_reps', 'small_isolation', false),
    ('JM press', '{}', 'triceps', ARRAY['chest'], 'barbell', 'elbow_extension', 'weight_reps', 'isolation', false),
    ('Bench dip', ARRAY['Tricep bench dip'], 'triceps', ARRAY['chest', 'front delts'], 'bodyweight', 'elbow_extension', 'bodyweight_reps', 'isolation', false),
    ('Leg curl (dumbbell)', ARRAY['Dumbbell hamstring curl'], 'hamstrings', '{}', 'dumbbell', 'leg_curl', 'weight_reps', 'isolation', false),
    ('Cable leg curl', ARRAY['Standing cable hamstring curl'], 'hamstrings', '{}', 'cable', 'leg_curl', 'weight_reps', 'isolation', false),
    ('Donkey calf raise', '{}', 'calves', '{}', 'machine', 'calf_raise', 'weight_reps', 'isolation', false),
    ('Reverse hyperextension', ARRAY['Reverse hyper'], 'glutes', ARRAY['hamstrings', 'back'], 'machine', 'hip_extension', 'weight_reps', 'isolation', false),
    ('Weighted pull-up', ARRAY['Pull-up weighted'], 'back', ARRAY['biceps', 'rear delts', 'core'], 'bodyweight', 'vertical_pull', 'bodyweight_reps', 'compound', false),
    ('Muscle-up', ARRAY['Bar muscle-up'], 'back', ARRAY['chest', 'triceps', 'core'], 'bodyweight', 'vertical_pull', 'bodyweight_reps', 'compound', false),
    ('Handstand push-up', ARRAY['HSPU', 'Wall handstand push-up'], 'shoulders', ARRAY['triceps', 'core'], 'bodyweight', 'vertical_press', 'reps_only', 'compound', false),
    ('Pike push-up', '{}', 'shoulders', ARRAY['triceps'], 'bodyweight', 'vertical_press', 'reps_only', 'compound', false),
    ('Dumbbell Y press', ARRAY['Y press'], 'shoulders', ARRAY['triceps'], 'dumbbell', 'vertical_press', 'weight_reps', 'compound', false),
    ('Standing calf raise (bodyweight, single leg)', ARRAY['Single leg calf raise'], 'calves', '{}', 'bodyweight', 'calf_raise', 'reps_only', 'isolation', false),
    ('Wrist roller', '{}', 'forearms', '{}', 'barbell', 'wrist_flexion', 'weight_reps', 'small_isolation', false),
    ('Plate pinch hold', ARRAY['Plate pinch'], 'forearms', '{}', 'barbell', 'grip', 'time', 'small_isolation', false),
    ('Suitcase carry', ARRAY['Single arm farmer''s walk'], 'core', ARRAY['forearms', 'traps', 'obliques'], 'dumbbell', 'carry', 'weight_reps', 'compound', false),
    ('Overhead carry', ARRAY['Waiter''s walk'], 'shoulders', ARRAY['core', 'traps'], 'dumbbell', 'carry', 'weight_reps', 'compound', false);

END $$;
